#Training args
model_name_or_path: /gaueko1/hizkuntza-ereduak/vicuna-13b
config_template: vicuna_v1.1
torch_dtype: "auto"
use_lora: false
int8_quantization: true
predict_with_generate: true
do_predict: true
per_device_eval_batch_size: 4

generation_args_json: /ikerlariak/igarcia945/CoLLIE/configs/pharapharse_config/generation_config.json
output_dir: /ikerlariak/igarcia945/CoLLIE/paraphrase/vicuna-13b


# dataset arguments
datasets:
  #- ace05
  - conll03
  #- rams
  #- tacred
language: en





# reporting
logging_strategy: steps
logging_first_step: true
logging_steps: 25
report_to: none


# hub settings
push_to_hub: false
resume_from_checkpoint: false

# performance
bf16: false
fp16: false
torch_compile: false
ddp_find_unused_parameters: false