#Training args
model_name_or_path: /gaueko1/hizkuntza-ereduak/LLaMA/lm/huggingface/7B/
torch_dtype: float32
use_lora: false
quantization: null
force_auto_device_map: true
#deepspeed: /ikerlariak/osainz006/CoLLIE/configs/deepspeed_configs/

# dataset arguments
dataset_dir:
  /ikerlariak/osainz006/CoLLIE/data/processed
train_tasks:
  - ace05.ner
  - ace05.re
  - ace05.rc
  - ace05.ee
  - ace05.eae
  - conll03.ner
  - rams.eae
validation_tasks:
  - ace05.ner
  - ace05.ver
  - ace05.re
  - ace05.rc
  - ace05.ee
  - ace05.eae
  - conll03.ner
  - rams.eae
test_tasks:
  - ace05.ner
  - ace05.ver
  - ace05.re
  - ace05.rc
  - ace05.ee
  - ace05.eae
  - conll03.ner
  - europarl.ner
  - rams.eae
max_seq_length: 2048
generation_max_length: 2048
ignore_pad_token_for_loss: true
prompt_loss_weight: 0.0

# checkpoint settings
output_dir: /ikerlariak/osainz006/models/collie/CoLLIE-7b_full_model_fp16
overwrite_output_dir: true
load_best_model_at_end: false
save_strategy: "epoch"
save_steps: 1000
save_total_limit: 999

# evaluation
do_train: true
do_eval: true
do_predict: true
evaluation_strategy: "steps"
eval_steps: 500
eval_delay: 0
predict_with_generate: true
evaluate_all_checkpoints: false

# batch size: 16 batch size * 8 gradaccum * 1 GPUs = 128
per_device_train_batch_size: 8
per_device_eval_batch_size: 4
gradient_accumulation_steps: 4
generation_num_beams: 1

# optimizer settings
optim: adamw_torch_fused
learning_rate: 0.0003
weight_decay: 0
num_train_epochs: 3
lr_scheduler_type: cosine
warmup_ratio: 0.03

# lora settings
lora_r: 16
lora_alpha: 16
lora_dropout: 0.05
lora_target_modules:
  - q_proj
  - v_proj
  - k_proj
  - o_proj

# reporting
logging_strategy: steps
logging_first_step: true
logging_steps: 25
report_to: wandb
#report_to: none
run_name: "CoLLIE-7b_full_model_fp16"
disable_tqdm: false

# hub settings
push_to_hub: false
resume_from_checkpoint: false

# performance
bf16: false
fp16: true
torch_compile: false
ddp_find_unused_parameters: false
