#Training args
model_name_or_path: /ikerlariak/osainz006/models/collie/CoLLIE-7b_LLaMA2_full_model_2
torch_dtype: bfloat16
use_lora: false
quantization: null
gradient_checkpointing: true
force_auto_device_map: false
use_flash_attention: true
#deepspeed: /ikerlariak/igarcia945/CoLLIE/configs/deepspeed_configs/deepspeed_zero3.json

# dataset arguments
dataset_dir:
  /ikerlariak/osainz006/CoLLIE/data/processed
test_tasks:
  - ace05.eae
  - ace05.ee
  - ace05.ner
  - ace05.rc
  - ace05.re
  - ace05.ver
  - bc5cdr.ner
  - conll03.ner
  - diann.ner
  - ncbidisease.ner
  - ontonotes5.ner
  - rams.eae
  - tacred.sf
  - wikievents.eae
  - wikievents.ee
  - wikievents.ner
  - wnut17.ner
  - e3c.ner
  - broadtwitter.ner
  - fabner.ner
  - harveyner.ner
  - multinerd.ner
  - casie.eae
  - casie.ee
  - mitmovie.ner
  - mitrestaurant.ner

max_examples_per_task_test: null
max_seq_length: 2048
generation_max_length: 2048
ignore_pad_token_for_loss: true
prompt_loss_weight: 0.0

# checkpoint settings
output_dir: /ikerlariak/osainz006/models/collie/CoLLIE-7b_LLaMA2_full_model
overwrite_output_dir: true

# evaluation
do_train: false
do_eval: false
do_predict: true
predict_with_generate: true
evaluate_all_checkpoints: true

# batch size: 16 batch size * 8 gradaccum * 1 GPUs = 128

per_device_eval_batch_size: 8
generation_num_beams: 1

# optimizer settings

# lora settings

# reporting
logging_strategy: steps
logging_first_step: true
logging_steps: 25
report_to: wandb
#report_to: none
run_name: "Eval_CoLLIE-7b_LLaMA2_full_model_2"
disable_tqdm: false

# hub settings
push_to_hub: false
resume_from_checkpoint: false

# performance
bf16: true
fp16: false
torch_compile: false
ddp_find_unused_parameters: false
