#Training args
model_name_or_path: /gaueko1/hizkuntza-ereduak/LLaMA/lm/huggingface/7B/
torch_dtype: None
use_lora: true
int8_quantization: true


# dataset arguments
dataset_dir:
  /gscratch4/users/osainz006/CoLLIE/data/processed
train_tasks:
  - ace05
  -
validation_files:
  - data/es.dev_casimedicos.jsonl
test_files:
  - data/es.test_casimedicos.jsonl
max_seq_length: 384
include_incorrect: true
ignore_pad_token_for_loss: false

# checkpoint settings
output_dir: results/casimedicos_MedicalmT5_xl
overwrite_output_dir: true
load_best_model_at_end: true
metric_for_best_model: es.dev_casimedicos_loss
greater_is_better: false
save_strategy: "epoch"
save_total_limit: 1

# evaluation
do_train: true
do_eval: true
do_predict: true
evaluation_strategy: "epoch"
eval_delay: 70
predict_with_generate: true

# batch size: 16 batch size * 8 gradaccum * 1 GPUs = 128
per_device_train_batch_size: 4
per_device_eval_batch_size: 4
gradient_accumulation_steps: 4
generation_num_beams: 4

# optimizer settings
optim: adafactor
learning_rate: 0.0001
weight_decay: 0
num_train_epochs: 100
lr_scheduler_type: cosine
warmup_ratio: 0.03

# lora settings
lora_r: 8
lora_alpha: 16
lora_dropout: 0.05

# reporting
logging_strategy: steps
logging_first_step: true
logging_steps: 10
report_to: wandb
#report_to: none
run_name: "MedicalmT5_xl_es_casimedicos"
disable_tqdm: false

# hub settings
push_to_hub: false
resume_from_checkpoint: false

# performance
bf16: true
fp16: false
torch_compile: false
ddp_find_unused_parameters: false