#Training args
model_name_or_path: /ikerlariak/igarcia945/CoLLIE/pretrained_models/CoLLIE-7B
lora_weights_name_or_path: /ikerlariak/igarcia945/CoLLIE/pretrained_models/CoLLIE-7B
torch_dtype: "auto"
use_lora: true
int8_quantization: true

# dataset arguments
dataset_dir:
  /gscratch4/users/osainz006/CoLLIE/data/processed
test_tasks:
  - ace05.ner
max_seq_length: 2048
generation_max_length: 2048
ignore_pad_token_for_loss: false

# checkpoint settings
output_dir: /ikerlariak/igarcia945/CoLLIE/pretrained_models/CoLLIE-7B
overwrite_output_dir: true
load_best_model_at_end: false
save_strategy: "no"
save_total_limit: 0

# evaluation
do_train: false
do_eval: false
do_predict: true
evaluation_strategy: "epoch"
eval_delay: 0
predict_with_generate: true

# batch size: 16 batch size * 8 gradaccum * 1 GPUs = 128
per_device_train_batch_size: 32
per_device_eval_batch_size: 32
gradient_accumulation_steps: 1
generation_num_beams: 1

# optimizer settings
optim: adamw_torch
learning_rate: 0.00005
weight_decay: 0
num_train_epochs: 1
lr_scheduler_type: cosine
warmup_ratio: 0.03

# lora settings
lora_r: 8
lora_alpha: 16
lora_dropout: 0.05

# reporting
logging_strategy: steps
logging_first_step: true
logging_steps: 25
report_to: wandb
#report_to: none
run_name: "CoLLIE-7B"
disable_tqdm: false

# hub settings
push_to_hub: false
resume_from_checkpoint: false

# performance
bf16: false
fp16: true
torch_compile: false
ddp_find_unused_parameters: false